/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 02 18:04:06 GMT 2026
 */

package org.apache.zookeeper.inspector.gui.nodeviewer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.apache.zookeeper.inspector.gui.nodeviewer.NodeViewerData;
import org.apache.zookeeper.inspector.gui.nodeviewer.NodeViewerDataEvoSuiteHelper;

public class NodeViewerDataEvoSuiteHelper_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NodeViewerDataEvoSuiteHelper nodeViewerDataEvoSuiteHelper0 = new NodeViewerDataEvoSuiteHelper();
      // Undeclared exception!
      try {
        nodeViewerDataEvoSuiteHelper0.selectNoNode((NodeViewerData) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.inspector.gui.nodeviewer.NodeViewerDataEvoSuiteHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NodeViewerDataEvoSuiteHelper nodeViewerDataEvoSuiteHelper0 = new NodeViewerDataEvoSuiteHelper();
      // Undeclared exception!
      try {
        nodeViewerDataEvoSuiteHelper0.getTitle((NodeViewerData) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.zookeeper.inspector.gui.nodeviewer.NodeViewerDataEvoSuiteHelper", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NodeViewerDataEvoSuiteHelper nodeViewerDataEvoSuiteHelper0 = new NodeViewerDataEvoSuiteHelper();
      NodeViewerData nodeViewerData0 = nodeViewerDataEvoSuiteHelper0.createViewer();
      String string0 = nodeViewerDataEvoSuiteHelper0.getTitle(nodeViewerData0);
      assertEquals("Node Data", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NodeViewerDataEvoSuiteHelper nodeViewerDataEvoSuiteHelper0 = new NodeViewerDataEvoSuiteHelper();
      List<String> list0 = nodeViewerDataEvoSuiteHelper0.createEmptySelection();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NodeViewerDataEvoSuiteHelper nodeViewerDataEvoSuiteHelper0 = new NodeViewerDataEvoSuiteHelper();
      NodeViewerData nodeViewerData0 = nodeViewerDataEvoSuiteHelper0.createViewer();
      nodeViewerDataEvoSuiteHelper0.selectNoNode(nodeViewerData0);
      assertFalse(nodeViewerData0.getIgnoreRepaint());
  }
}
