package org.apache.jute.compiler;

import java.lang.reflect.Field;

import org.junit.AfterClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class JVectorRandoopPart1Test {

    public static boolean debug = false;

    public void assertBooleanArrayEquals(boolean[] expectedArray, boolean[] actualArray) {
        if (expectedArray.length != actualArray.length) {
            throw new AssertionError("Array lengths differ: " + expectedArray.length + " != " + actualArray.length);
        }
        for (int i = 0; i < expectedArray.length; i++) {
            if (expectedArray[i] != actualArray[i]) {
                throw new AssertionError("Arrays differ at index " + i + ": " + expectedArray[i] + " != " + actualArray[i]);
            }
        }
    }

    @Test
    public void test501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "JVectorRandoopPart1Test.test501");
        org.apache.jute.compiler.JString jString0 = new org.apache.jute.compiler.JString();
        java.lang.String str3 = jString0.genJavaWriteWrapper("", "  int \n");
        java.lang.String str6 = jString0.genJavaWriteWrapper("", "i");
        java.lang.String str9 = jString0.genJavaWriteWrapper("  private string ;\n", "    {\n      Index vidx1 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx1!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx1.done(); vidx1.incr()) {\n    String e1;\n        e1=a_.readString(\"e1\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e1);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n");
        org.apache.jute.compiler.JVector jVector10 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jString0);
        java.lang.String str13 = jVector10.genJavaReadMethod("s", "");
        java.lang.String str16 = jVector10.genCsharpWriteMethod("  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n", "    throw new UnsupportedOperationException(\"comparing         =a_.readString(\"Int_vector\");\n is unimplemented\");\n");
        org.apache.jute.compiler.JType jType17 = jVector10.getElementType();
        org.apache.jute.compiler.JType jType18 = jVector10.getElementType();
        java.lang.String str19 = jVector10.getSignature();
        org.junit.Assert.assertEquals("'" + str3 + "' != '" + "        a_.writeString(,\"  int \n\");\n" + "'", str3, "        a_.writeString(,\"  int \n\");\n");
        org.junit.Assert.assertEquals("'" + str6 + "' != '" + "        a_.writeString(,\"i\");\n" + "'", str6, "        a_.writeString(,\"i\");\n");
        org.junit.Assert.assertEquals("'" + str9 + "' != '" + "        a_.writeString(  private string ;\n,\"    {\n      Index vidx1 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx1!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx1.done(); vidx1.incr()) {\n    String e1;\n        e1=a_.readString(\"e1\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e1);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n\");\n" + "'", str9, "        a_.writeString(  private string ;\n,\"    {\n      Index vidx1 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx1!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx1.done(); vidx1.incr()) {\n    String e1;\n        e1=a_.readString(\"e1\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e1);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n\");\n");
// flaky "1) test501(org.apache.jute.compiler.JVectorRandoopPart1Test)":         org.junit.Assert.assertEquals("'" + str13 + "' != '" + "    {\n      Index vidx20 = a_.startVector(\"\");\n      if (vidx20!= null) {          s=new java.util.ArrayList<String>();\n          for (; !vidx20.done(); vidx20.incr()) {\n    String e20;\n        e20=a_.readString(\"e20\");\n            s.add(e20);\n          }\n      }\n    a_.endVector(\"\");\n    }\n" + "'", str13, "    {\n      Index vidx20 = a_.startVector(\"\");\n      if (vidx20!= null) {          s=new java.util.ArrayList<String>();\n          for (; !vidx20.done(); vidx20.incr()) {\n    String e20;\n        e20=a_.readString(\"e20\");\n            s.add(e20);\n          }\n      }\n    a_.endVector(\"\");\n    }\n");
// flaky "1) test501(org.apache.jute.compiler.JVectorRandoopPart1Test)":         org.junit.Assert.assertEquals("'" + str16 + "' != '" + "    {\n      a_.StartVector(  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n,\"    throw new UnsupportedOperationException(\"comparing         =a_.readString(\"Int_vector\");\n is unimplemented\");\n\");\n      if (  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n!= null) {          int len20 =   System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n.Count;\n          for(int vidx20 = 0; vidx20<len20; vidx20++) {\n            string e20 = (string)   System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n[vidx20];\n        a_.WriteString(e20,e20);\n          }\n      }\n      a_.EndVector(  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n,\"    throw new UnsupportedOperationException(\"comparing         =a_.readString(\"Int_vector\");\n is unimplemented\");\n\");\n    }\n" + "'", str16, "    {\n      a_.StartVector(  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n,\"    throw new UnsupportedOperationException(\"comparing         =a_.readString(\"Int_vector\");\n is unimplemented\");\n\");\n      if (  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n!= null) {          int len20 =   System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n.Count;\n          for(int vidx20 = 0; vidx20<len20; vidx20++) {\n            string e20 = (string)   System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n[vidx20];\n        a_.WriteString(e20,e20);\n          }\n      }\n      a_.EndVector(  System.Collections.Generic.List<int>         a_.writeString(,\"  int \n\");\n\n,\"    throw new UnsupportedOperationException(\"comparing         =a_.readString(\"Int_vector\");\n is unimplemented\");\n\");\n    }\n");
        org.junit.Assert.assertNotNull(jType17);
        org.junit.Assert.assertNotNull(jType18);
        org.junit.Assert.assertEquals("'" + str19 + "' != '" + "[s]" + "'", str19, "[s]");
    }

    @Test
    public void test502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "JVectorRandoopPart1Test.test502");
        org.apache.jute.compiler.JString jString0 = new org.apache.jute.compiler.JString();
        java.lang.String str3 = jString0.genJavaWriteWrapper("", "  int \n");
        java.lang.String str5 = jString0.genCsharpConstructorParam("    {\n      IIndex vidx1 = a_.StartVector(\"s\");\n      if (vidx1!= null) {          I=new System.Collections.Generic.List<int>();\n          for (; !vidx1.Done(); vidx1.Incr()) {\n    Integer e1;\n    e1=a_.ReadInt(\"e1\");\n            I.Add(e1);\n          }\n      }\n    a_.EndVector(\"s\");\n    }\n");
        org.apache.jute.compiler.JVector jVector6 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jString0);
        org.apache.jute.compiler.JVector jVector7 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jVector6);
        java.lang.String str10 = jVector7.genJavaReadMethod("  private int i;\n", "[s]");
        org.apache.jute.compiler.JType jType11 = jVector7.getElementType();
        java.lang.String str12 = jVector7.getSignature();
        org.apache.jute.compiler.JVector jVector13 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jVector7);
        java.lang.String str15 = jVector13.genJavaCompareTo("  private int     {\n      a_.StartVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n      if (  private string         a_.writeString(,\"i\");\n;\n!= null) {          int len4 =   private string         a_.writeString(,\"i\");\n;\n.Count;\n          for(int vidx4 = 0; vidx4<len4; vidx4++) {\n            string e4 = (string)   private string         a_.writeString(,\"i\");\n;\n[vidx4];\n        a_.WriteString(e4,e4);\n          }\n      }\n      a_.EndVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n    }\n;\n");
        org.junit.Assert.assertEquals("'" + str3 + "' != '" + "        a_.writeString(,\"  int \n\");\n" + "'", str3, "        a_.writeString(,\"  int \n\");\n");
        org.junit.Assert.assertEquals("'" + str5 + "' != '" + "  string     {\n      IIndex vidx1 = a_.StartVector(\"s\");\n      if (vidx1!= null) {          I=new System.Collections.Generic.List<int>();\n          for (; !vidx1.Done(); vidx1.Incr()) {\n    Integer e1;\n    e1=a_.ReadInt(\"e1\");\n            I.Add(e1);\n          }\n      }\n    a_.EndVector(\"s\");\n    }\n\n" + "'", str5, "  string     {\n      IIndex vidx1 = a_.StartVector(\"s\");\n      if (vidx1!= null) {          I=new System.Collections.Generic.List<int>();\n          for (; !vidx1.Done(); vidx1.Incr()) {\n    Integer e1;\n    e1=a_.ReadInt(\"e1\");\n            I.Add(e1);\n          }\n      }\n    a_.EndVector(\"s\");\n    }\n\n");
// flaky "2) test502(org.apache.jute.compiler.JVectorRandoopPart1Test)":         org.junit.Assert.assertEquals("'" + str10 + "' != '" + "    {\n      Index vidx20 = a_.startVector(\"[s]\");\n      if (vidx20!= null) {            private int i;\n=new java.util.ArrayList<java.util.List<String>>();\n          for (; !vidx20.done(); vidx20.incr()) {\n      java.util.List e20;\n    {\n      Index vidx21 = a_.startVector(\"e20\");\n      if (vidx21!= null) {          e20=new java.util.ArrayList<String>();\n          for (; !vidx21.done(); vidx21.incr()) {\n    String e21;\n        e21=a_.readString(\"e21\");\n            e20.add(e21);\n          }\n      }\n    a_.endVector(\"e20\");\n    }\n              private int i;\n.add(e20);\n          }\n      }\n    a_.endVector(\"[s]\");\n    }\n" + "'", str10, "    {\n      Index vidx20 = a_.startVector(\"[s]\");\n      if (vidx20!= null) {            private int i;\n=new java.util.ArrayList<java.util.List<String>>();\n          for (; !vidx20.done(); vidx20.incr()) {\n      java.util.List e20;\n    {\n      Index vidx21 = a_.startVector(\"e20\");\n      if (vidx21!= null) {          e20=new java.util.ArrayList<String>();\n          for (; !vidx21.done(); vidx21.incr()) {\n    String e21;\n        e21=a_.readString(\"e21\");\n            e20.add(e21);\n          }\n      }\n    a_.endVector(\"e20\");\n    }\n              private int i;\n.add(e20);\n          }\n      }\n    a_.endVector(\"[s]\");\n    }\n");
        org.junit.Assert.assertNotNull(jType11);
        org.junit.Assert.assertEquals("'" + str12 + "' != '" + "[[s]]" + "'", str12, "[[s]]");
        org.junit.Assert.assertEquals("'" + str15 + "' != '" + "    throw new UnsupportedOperationException(\"comparing   private int     {\n      a_.StartVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n      if (  private string         a_.writeString(,\"i\");\n;\n!= null) {          int len4 =   private string         a_.writeString(,\"i\");\n;\n.Count;\n          for(int vidx4 = 0; vidx4<len4; vidx4++) {\n            string e4 = (string)   private string         a_.writeString(,\"i\");\n;\n[vidx4];\n        a_.WriteString(e4,e4);\n          }\n      }\n      a_.EndVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n    }\n;\n is unimplemented\");\n" + "'", str15, "    throw new UnsupportedOperationException(\"comparing   private int     {\n      a_.StartVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n      if (  private string         a_.writeString(,\"i\");\n;\n!= null) {          int len4 =   private string         a_.writeString(,\"i\");\n;\n.Count;\n          for(int vidx4 = 0; vidx4<len4; vidx4++) {\n            string e4 = (string)   private string         a_.writeString(,\"i\");\n;\n[vidx4];\n        a_.WriteString(e4,e4);\n          }\n      }\n      a_.EndVector(  private string         a_.writeString(,\"i\");\n;\n,\"hi!\");\n    }\n;\n is unimplemented\");\n");
    }

    @Test
    public void test503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "JVectorRandoopPart1Test.test503");
        org.apache.jute.compiler.JInt jInt0 = new org.apache.jute.compiler.JInt();
        java.lang.String str2 = jInt0.genCsharpConstructorParam("");
        java.lang.String str4 = jInt0.genCsharpConstructorParam("");
        org.apache.jute.compiler.JVector jVector5 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jInt0);
        java.lang.String str7 = jVector5.genJavaCompareTo("    {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n");
        java.lang.String str9 = jVector5.genCsharpConstructorParam("    {\n      a_.StartVector(Int_vector,\"Int_vector\");\n      if (Int_vector!= null) {          int len2 = Int_vector.Count;\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            string e2 = (string) Int_vector[vidx2];\n        a_.WriteString(e2,e2);\n          }\n      }\n      a_.EndVector(Int_vector,\"Int_vector\");\n    }\n");
        org.apache.jute.compiler.JType jType10 = jVector5.getElementType();
        java.lang.String str12 = jVector5.genJavaCompareTo("i");
        // The following exception was thrown during execution in test generation
        try {
            java.lang.String str15 = jVector5.genCsharpWriteMethod("", "        a_.writeString(    {\n      Index vidx1 = a_.startVector(\"        a_.writeString(,\"i\");\n\");\n      if (vidx1!= null) {          s=new java.util.ArrayList<int>();\n          for (; !vidx1.done(); vidx1.incr()) {\n    Integer e1;\n    e1=new Integer(a_.readInt(\"e1\"));\n            s.add(e1);\n          }\n      }\n    a_.endVector(\"        a_.writeString(,\"i\");\n\");\n    }\n,\"  private int     {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len4 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx4 = 0; vidx4<len4; vidx4++) {\n            String e4 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx4);\n        a_.writeString(e4,\"e4\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n;\n\");\n");
            org.junit.Assert.fail("Expected exception of type java.lang.StringIndexOutOfBoundsException; message: Range [0, 1) out of bounds for length 0");
        } catch (java.lang.StringIndexOutOfBoundsException e) {
            // Expected exception.
        }
        org.junit.Assert.assertEquals("'" + str2 + "' != '" + "  int \n" + "'", str2, "  int \n");
        org.junit.Assert.assertEquals("'" + str4 + "' != '" + "  int \n" + "'", str4, "  int \n");
        org.junit.Assert.assertEquals("'" + str7 + "' != '" + "    throw new UnsupportedOperationException(\"comparing     {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n is unimplemented\");\n" + "'", str7, "    throw new UnsupportedOperationException(\"comparing     {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n is unimplemented\");\n");
        org.junit.Assert.assertEquals("'" + str9 + "' != '" + "  System.Collections.Generic.List<int>     {\n      a_.StartVector(Int_vector,\"Int_vector\");\n      if (Int_vector!= null) {          int len2 = Int_vector.Count;\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            string e2 = (string) Int_vector[vidx2];\n        a_.WriteString(e2,e2);\n          }\n      }\n      a_.EndVector(Int_vector,\"Int_vector\");\n    }\n\n" + "'", str9, "  System.Collections.Generic.List<int>     {\n      a_.StartVector(Int_vector,\"Int_vector\");\n      if (Int_vector!= null) {          int len2 = Int_vector.Count;\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            string e2 = (string) Int_vector[vidx2];\n        a_.WriteString(e2,e2);\n          }\n      }\n      a_.EndVector(Int_vector,\"Int_vector\");\n    }\n\n");
        org.junit.Assert.assertNotNull(jType10);
        org.junit.Assert.assertEquals("'" + str12 + "' != '" + "    throw new UnsupportedOperationException(\"comparing i is unimplemented\");\n" + "'", str12, "    throw new UnsupportedOperationException(\"comparing i is unimplemented\");\n");
    }

    @Test
    public void test504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "JVectorRandoopPart1Test.test504");
        org.apache.jute.compiler.JString jString0 = new org.apache.jute.compiler.JString();
        java.lang.String str4 = jString0.genJavaReadWrapper("", "", false);
        org.apache.jute.compiler.JVector jVector5 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jString0);
        java.lang.String str8 = jVector5.genJavaWriteWrapper("        a_.writeString(,\"  int \n\");\n", "");
        org.apache.jute.compiler.JVector jVector9 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jVector5);
        java.lang.String str11 = jVector9.genJavaCompareTo("    {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len2 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            String e2 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx2);\n        a_.writeString(e2,\"e2\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n");
        org.apache.jute.compiler.JVector jVector12 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jVector9);
        java.lang.String str14 = jVector12.genCsharpDecl("    {\n      Index vidx18 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx18!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx18.done(); vidx18.incr()) {\n    String e18;\n        e18=a_.readString(\"e18\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e18);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n");
        org.junit.Assert.assertEquals("'" + str4 + "' != '" + "        =a_.readString(\"\");\n" + "'", str4, "        =a_.readString(\"\");\n");
// flaky "3) test504(org.apache.jute.compiler.JVectorRandoopPart1Test)":         org.junit.Assert.assertEquals("'" + str8 + "' != '" + "    {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len21 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx21 = 0; vidx21<len21; vidx21++) {\n            String e21 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx21);\n        a_.writeString(e21,\"e21\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n" + "'", str8, "    {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len21 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx21 = 0; vidx21<len21; vidx21++) {\n            String e21 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx21);\n        a_.writeString(e21,\"e21\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n");
        org.junit.Assert.assertEquals("'" + str11 + "' != '" + "    throw new UnsupportedOperationException(\"comparing     {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len2 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            String e2 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx2);\n        a_.writeString(e2,\"e2\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n is unimplemented\");\n" + "'", str11, "    throw new UnsupportedOperationException(\"comparing     {\n      a_.startVector(        a_.writeString(,\"  int \n\");\n,\"\");\n      if (        a_.writeString(,\"  int \n\");\n!= null) {          int len2 =         a_.writeString(,\"  int \n\");\n.size();\n          for(int vidx2 = 0; vidx2<len2; vidx2++) {\n            String e2 = (String)         a_.writeString(,\"  int \n\");\n.get(vidx2);\n        a_.writeString(e2,\"e2\");\n          }\n      }\n      a_.endVector(        a_.writeString(,\"  int \n\");\n,\"\");\n    }\n is unimplemented\");\n");
        org.junit.Assert.assertEquals("'" + str14 + "' != '" + "  private System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<string>>>     {\n      Index vidx18 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx18!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx18.done(); vidx18.incr()) {\n    String e18;\n        e18=a_.readString(\"e18\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e18);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n;\n" + "'", str14, "  private System.Collections.Generic.List<System.Collections.Generic.List<System.Collections.Generic.List<string>>>     {\n      Index vidx18 = a_.startVector(\"        =a_.readString(\"\");\n\");\n      if (vidx18!= null) {              String ;\n        =a_.readString(\"hi!\");\n=new java.util.ArrayList<String>();\n          for (; !vidx18.done(); vidx18.incr()) {\n    String e18;\n        e18=a_.readString(\"e18\");\n                String ;\n        =a_.readString(\"hi!\");\n.add(e18);\n          }\n      }\n    a_.endVector(\"        =a_.readString(\"\");\n\");\n    }\n;\n");
    }

    @Test
    public void test505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "JVectorRandoopPart1Test.test505");
        org.apache.jute.compiler.JInt jInt0 = new org.apache.jute.compiler.JInt();
        java.lang.String str2 = jInt0.genCsharpConstructorParam("");
        java.lang.String str4 = jInt0.genCsharpConstructorParam("");
        org.apache.jute.compiler.JVector jVector5 = new org.apache.jute.compiler.JVector((org.apache.jute.compiler.JType) jInt0);
        java.lang.String str7 = jVector5.genJavaCompareTo("    {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n");
        java.lang.String str9 = jVector5.genCsharpConstructorParam("    throw new UnsupportedOperationException(\"comparing   private int     {\n      IIndex vidx2 = a_.StartVector(\"\");\n      if (vidx2!= null) {                  =a_.readString(\"Int_vector\");\n=new System.Collections.Generic.List<string>();\n          for (; !vidx2.Done(); vidx2.Incr()) {\n    String e2;\n    e2=a_.ReadString(\"e2\");\n                    =a_.readString(\"Int_vector\");\n.Add(e2);\n          }\n      }\n    a_.EndVector(\"\");\n    }\n;\n is unimplemented\");\n");
        org.junit.Assert.assertEquals("'" + str2 + "' != '" + "  int \n" + "'", str2, "  int \n");
        org.junit.Assert.assertEquals("'" + str4 + "' != '" + "  int \n" + "'", str4, "  int \n");
        org.junit.Assert.assertEquals("'" + str7 + "' != '" + "    throw new UnsupportedOperationException(\"comparing     {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n is unimplemented\");\n" + "'", str7, "    throw new UnsupportedOperationException(\"comparing     {\n      a_.StartVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n      if (Hi!!= null) {          int len1 = Hi!.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            int e1 = (int) Hi![vidx1];\n        a_.WriteInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.EndVector(Hi!,\"    {\n      a_.startVector(s,\"s\");\n      if (s!= null) {          int len1 = s.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            Integer e1 = (Integer) s.get(vidx1);\n        a_.writeInt(e1.toInt(),\"e1\");\n          }\n      }\n      a_.endVector(s,\"s\");\n    }\n\");\n    }\n is unimplemented\");\n");
        org.junit.Assert.assertEquals("'" + str9 + "' != '" + "  System.Collections.Generic.List<int>     throw new UnsupportedOperationException(\"comparing   private int     {\n      IIndex vidx2 = a_.StartVector(\"\");\n      if (vidx2!= null) {                  =a_.readString(\"Int_vector\");\n=new System.Collections.Generic.List<string>();\n          for (; !vidx2.Done(); vidx2.Incr()) {\n    String e2;\n    e2=a_.ReadString(\"e2\");\n                    =a_.readString(\"Int_vector\");\n.Add(e2);\n          }\n      }\n    a_.EndVector(\"\");\n    }\n;\n is unimplemented\");\n\n" + "'", str9, "  System.Collections.Generic.List<int>     throw new UnsupportedOperationException(\"comparing   private int     {\n      IIndex vidx2 = a_.StartVector(\"\");\n      if (vidx2!= null) {                  =a_.readString(\"Int_vector\");\n=new System.Collections.Generic.List<string>();\n          for (; !vidx2.Done(); vidx2.Incr()) {\n    String e2;\n    e2=a_.ReadString(\"e2\");\n                    =a_.readString(\"Int_vector\");\n.Add(e2);\n          }\n      }\n    a_.EndVector(\"\");\n    }\n;\n is unimplemented\");\n\n");
    }

    @AfterClass
    public static void resetJVectorLevel() throws Exception {
        Field level = JVector.class.getDeclaredField("level");
        level.setAccessible(true);
        level.setInt(null, 0);
    }
}
