/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 01 15:19:53 GMT 2026
 */

package org.apache.jute.compiler;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.jute.compiler.JBuffer;
import org.apache.jute.compiler.JByte;
import org.apache.jute.compiler.JDouble;
import org.apache.jute.compiler.JFloat;
import org.apache.jute.compiler.JInt;
import org.apache.jute.compiler.JLong;
import org.apache.jute.compiler.JMap;
import org.apache.jute.compiler.JType;
import org.apache.jute.compiler.JVector;
import java.lang.reflect.Field;
import org.junit.Before;

public class JVector_ESTest {

    @Before
    public void resetJVectorLevel() throws Exception {
        Field level = JVector.class.getDeclaredField("level");
        level.setAccessible(true);
        level.setInt(null, 0);
    }

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genCsharpReadMethod("6Jii&F^,|s?", "        new BinaryOutputArchive(writer);\n");
      assertEquals("    {\n      IIndex vidx1 = a_.StartVector(\"        new BinaryOutputArchive(writer);\n\");\n      if (vidx1!= null) {          6Jii&F^,|s?=new System.Collections.Generic.List<byte[]>();\n          for (; !vidx1.Done(); vidx1.Incr()) {\n    byte[] e1;\n    e1=a_.ReadBuffer(\"e1\");\n            6Jii&F^,|s?.Add(e1);\n          }\n      }\n    a_.EndVector(\"        new BinaryOutputArchive(writer);\n\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genCsharpReadWrapper("D`", "wu5>&ECldj", true);
      assertEquals("      System.Collections.Generic.List<byte[]> D`;\n    {\n      IIndex vidx1 = a_.StartVector(\"wu5>&ECldj\");\n      if (vidx1!= null) {          D`=new System.Collections.Generic.List<byte[]>();\n          for (; !vidx1.Done(); vidx1.Incr()) {\n    byte[] e1;\n    e1=a_.ReadBuffer(\"e1\");\n            D`.Add(e1);\n          }\n      }\n    a_.EndVector(\"wu5>&ECldj\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      JInt jInt0 = new JInt();
      JMap jMap0 = new JMap(jInt0, jInt0);
      JVector jVector0 = new JVector(jMap0);
      String string0 = jVector0.genJavaWriteMethod("", "");
      assertEquals("    {\n      a_.startVector(,\"\");\n      if (!= null) {          int len1 = .size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            System.Collections.Generic.SortedDictionary<string, string> e1 = (System.Collections.Generic.SortedDictionary<string, string>) .get(vidx1);\n    {\n      a_.startMap(e1,\"e1\");\n      java.util.Set es1 = e1.entrySet();\n      for(java.util.Iterator midx1 = es1.iterator(); midx1.hasNext(); ) {\n        java.util.Map.Entry me1 = (java.util.Map.Entry) midx1.next();\n        Integer k1 = (Integer) me1.getKey();\n        Integer v1 = (Integer) me1.getValue();\n        a_.writeInt(k1.toInt(),\"k1\");\n        a_.writeInt(v1.toInt(),\"v1\");\n      }\n      a_.endMap(e1,\"e1\");\n    }\n          }\n      }\n      a_.endVector(,\"\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genJavaWriteWrapper("\u0004", "");
      assertEquals("    {\n      a_.startVector(\u0004,\"\");\n      if (\u0004!= null) {          int len1 = \u0004.size();\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            byte[] e1 = (byte[]) \u0004.get(vidx1);\n        a_.writeBuffer(e1,\"e1\");\n          }\n      }\n      a_.endVector(\u0004,\"\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JLong jLong0 = new JLong();
      JVector jVector0 = new JVector(jLong0);
      String string0 = jVector0.genCsharpWriteWrapper("y1`Z=Jxg5'Tg(H", "D0gof,5YHh8vMO");
      assertEquals("    {\n      a_.StartVector(Y1`Z=Jxg5'Tg(H,\"D0gof,5YHh8vMO\");\n      if (Y1`Z=Jxg5'Tg(H!= null) {          int len1 = Y1`Z=Jxg5'Tg(H.Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            long e1 = (long) Y1`Z=Jxg5'Tg(H[vidx1];\n        a_.WriteLong(e1.toLong(),\"e1\");\n          }\n      }\n      a_.EndVector(Y1`Z=Jxg5'Tg(H,\"D0gof,5YHh8vMO\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      JFloat jFloat0 = new JFloat();
      String string0 = JVector.extractVectorName(jFloat0);
      assertEquals("Float_vector", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      JByte jByte0 = new JByte();
      JVector jVector0 = new JVector(jByte0);
      // Undeclared exception!
      try {
        jVector0.genCsharpWriteWrapper((String) null, (String) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JType", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      JFloat jFloat0 = new JFloat();
      JVector jVector0 = new JVector(jFloat0);
      // Undeclared exception!
      try {
        jVector0.genCsharpWriteMethod("", "");
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      JByte jByte0 = new JByte();
      JVector jVector0 = new JVector(jByte0);
      // Undeclared exception!
      try {
        jVector0.genCsharpWriteMethod((String) null, (String) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JType", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      JFloat jFloat0 = new JFloat();
      JVector jVector0 = new JVector(jFloat0);
      // Undeclared exception!
      try {
        jVector0.genCsharpReadWrapper("", "", false);
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      // Undeclared exception!
      try {
        jVector0.genCsharpReadWrapper((String) null, (String) null, false);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JType", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JDouble jDouble0 = new JDouble();
      JVector jVector0 = new JVector(jDouble0);
      // Undeclared exception!
      try {
        jVector0.genCsharpReadMethod("", "");
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      // Undeclared exception!
      try {
        jVector0.genCsharpReadMethod((String) null, (String) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JType", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      // Undeclared exception!
      try {
        JVector.extractVectorName((JType) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JRecord", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      JVector jVector0 = null;
      try {
        jVector0 = new JVector((JType) null);
        fail("Expecting exception: NullPointerException");

      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.jute.compiler.JRecord", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      // Undeclared exception!
      try {
        jVector0.genCsharpWriteWrapper("", "");
        fail("Expecting exception: StringIndexOutOfBoundsException");

      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      JVector jVector1 = new JVector(jVector0);
      String string0 = jVector1.genJavaReadWrapper("Bykv{Gp@_", "[B]", false);
      assertEquals("    {\n      Index vidx1 = a_.startVector(\"[B]\");\n      if (vidx1!= null) {          Bykv{Gp@_=new java.util.ArrayList<java.util.List<byte[]>>();\n          for (; !vidx1.done(); vidx1.incr()) {\n      java.util.List e1;\n    {\n      Index vidx2 = a_.startVector(\"e1\");\n      if (vidx2!= null) {          e1=new java.util.ArrayList<byte[]>();\n          for (; !vidx2.done(); vidx2.incr()) {\n    byte[] e2;\n        e2=a_.readBuffer(\"e2\");\n            e1.add(e2);\n          }\n      }\n    a_.endVector(\"e1\");\n    }\n            Bykv{Gp@_.add(e1);\n          }\n      }\n    a_.endVector(\"[B]\");\n    }\n", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genJavaCompareTo("data[i]");
      assertEquals("    throw new UnsupportedOperationException(\"comparing data[i] is unimplemented\");\n", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genJavaReadMethod("vidx", "    {\n      Index vidx1 = a_.startVector(\"[B]\");\n      if (vidx1!= null) {          Bykv{Gp@_=new java.util.ArrayList<java.util.List<byte[]>>();\n          for (; !vidx1.done(); vidx1.incr()) {\n      java.util.List e1;\n    {\n      Index vidx2 = a_.startVector(\"e1\");\n      if (vidx2!= null) {          e1=new java.util.ArrayList<byte[]>();\n          for (; !vidx2.done(); vidx2.incr()) {\n    byte[] e2;\n        e2=a_.readBuffer(\"e2\");\n            e1.add(e2);\n          }\n      }\n    a_.endVector(\"e1\");\n    }\n            Bykv{Gp@_.add(e1);\n          }\n      }\n    a_.endVector(\"[B]\");\n    }\n");
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      JType jType0 = jVector0.getElementType();
      assertSame(jBuffer0, jType0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.getSignature();
      assertEquals("[B]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      JBuffer jBuffer0 = new JBuffer();
      JVector jVector0 = new JVector(jBuffer0);
      String string0 = jVector0.genCsharpWriteMethod("[B]", "D`");
      assertEquals("    {\n      a_.StartVector([B],\"D`\");\n      if ([B]!= null) {          int len1 = [B].Count;\n          for(int vidx1 = 0; vidx1<len1; vidx1++) {\n            byte[] e1 = (byte[]) [B][vidx1];\n        a_.WriteBuffer(e1,e1);\n          }\n      }\n      a_.EndVector([B],\"D`\");\n    }\n", string0);
  }
}
